AREAS = {
    "ai.general": {
        "label": "AI / General",
        "arxiv": ["cs.AI"],
        "openalex": ["Artificial intelligence"],
        "semanticscholar": ["Computer Science"],
        "boost": ["artificial intelligence", "intelligent systems"],
    },
    "ai.ml": {
        "label": "AI / Machine Learning",
        "arxiv": ["cs.LG", "stat.ML"],
        "openalex": ["Machine learning"],
        "semanticscholar": ["Computer Science"],
        "boost": ["machine learning", "deep learning"],
    },
    "ai.rl": {
        "label": "AI / Reinforcement Learning",
        "arxiv": ["cs.LG", "cs.AI", "stat.ML", "cs.RO"],
        "openalex": ["Reinforcement learning"],
        "semanticscholar": ["Computer Science"],
        "boost": ["reinforcement learning", "policy gradient", "actor critic", "q learning"],
    },
    "ai.cv": {
        "label": "AI / Vision",
        "arxiv": ["cs.CV"],
        "openalex": ["Computer vision"],
        "semanticscholar": ["Computer Science"],
        "boost": ["computer vision", "image understanding", "visual recognition"],
    },
    "ai.nlp": {
        "label": "AI / NLP",
        "arxiv": ["cs.CL"],
        "openalex": ["Natural language processing"],
        "semanticscholar": ["Computer Science"],
        "boost": ["natural language processing", "language model", "text generation"],
    },
    "ai.robotics": {
        "label": "AI / Robotics",
        "arxiv": ["cs.RO"],
        "openalex": ["Robotics"],
        "semanticscholar": ["Computer Science"],
        "boost": ["robotics", "robot learning", "autonomous systems"],
    },
    "ai.ir": {
        "label": "AI / Information Retrieval",
        "arxiv": ["cs.IR"],
        "openalex": ["Information retrieval"],
        "semanticscholar": ["Computer Science"],
        "boost": ["information retrieval", "search ranking", "retrieval systems"],
    },
    "ai.multi_agent": {
        "label": "AI / Multi-Agent",
        "arxiv": ["cs.MA", "cs.AI"],
        "openalex": ["Multi-agent systems"],
        "semanticscholar": ["Computer Science"],
        "boost": ["multi agent", "agent coordination", "game theoretic learning"],
    },
    "ai.safety": {
        "label": "AI / Safety",
        "arxiv": ["cs.AI", "cs.LG"],
        "openalex": ["Artificial intelligence"],
        "semanticscholar": ["Computer Science"],
        "boost": ["ai safety", "alignment", "robustness", "safe reinforcement learning"],
    },
    "ai.reasoning": {
        "label": "AI / Reasoning",
        "arxiv": ["cs.AI", "cs.LO"],
        "openalex": ["Artificial intelligence"],
        "semanticscholar": ["Computer Science"],
        "boost": ["automated reasoning", "symbolic reasoning", "logical inference"],
    },
    "cs.graphics": {
        "label": "CS / Graphics",
        "arxiv": ["cs.GR"],
        "openalex": ["Computer graphics"],
        "semanticscholar": ["Computer Science"],
        "boost": ["computer graphics", "rendering", "3d reconstruction"],
    },
    "math.general": {
        "label": "Mathematics",
        "arxiv": ["math"],
        "openalex": ["Mathematics"],
        "semanticscholar": ["Mathematics"],
        "boost": ["mathematics", "theorem", "proof"],
    },
    "stat.general": {
        "label": "Statistics",
        "arxiv": ["stat"],
        "openalex": ["Statistics"],
        "semanticscholar": ["Mathematics"],
        "boost": ["statistics", "statistical inference", "probabilistic modeling"],
    },
    "physics.general": {
        "label": "Physics",
        "arxiv": ["physics", "astro-ph"],
        "openalex": ["Physics"],
        "semanticscholar": ["Physics"],
        "boost": ["physics", "quantum", "astrophysics"],
    },
    "bio.general": {
        "label": "Biology",
        "arxiv": ["q-bio"],
        "openalex": ["Biology"],
        "semanticscholar": ["Biology"],
        "boost": ["biology", "genomics", "bioinformatics"],
    },
    "med.general": {
        "label": "Medicine",
        "arxiv": [],
        "openalex": ["Medicine"],
        "semanticscholar": ["Medicine"],
        "boost": ["medicine", "clinical", "medical diagnosis"],
    },
    "econ.general": {
        "label": "Economics",
        "arxiv": ["econ"],
        "openalex": ["Economics"],
        "semanticscholar": ["Economics"],
        "boost": ["economics", "econometrics", "market equilibrium"],
    },
    "fin.general": {
        "label": "Finance",
        "arxiv": ["q-fin"],
        "openalex": ["Finance"],
        "semanticscholar": ["Economics"],
        "boost": ["finance", "asset pricing", "portfolio optimization", "risk management"],
    },
}
